config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :entries,       only: [:index]
  resources :videos,        only: [:index, :new, :create]
  resources :video_uploads, only: [:new, :create]
  resources :comments,      only: [:new, :create]
  resources :messages,      only: [:new, :create, :index]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy', as: :logout
  get    'about'    => 'static_pages#about'
  get    'social'   => 'static_pages#social'
  get    'search'   => 'search#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  match '*path' => 'application#routing_error', via: :all
  
end

app/models/video.rb
class Video < ActiveRecord::Base
	YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
 
  validates :link, presence: true, format: YT_LINK_FORMAT
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
    @videos = Video.order('created_at DESC')
  end
 
  def new
    @video = Video.new
  end
 
  def create
	  @video = Video.new(video_params)
	  if @video.save
	    flash[:success] = 'Video added!'
	    redirect_to videos_path
	  else
	    render :new
	  end
	end
 
private
 
	def video_params
	  params.require(:video).permit(:link)
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="jumbotron">
  <div class="container">
    <h1>Share your sports videos!</h1>
    <p>Click the button below to share your video from YouTube.</p>
    <p>
      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>
 
<% if @videos.any? %>
  <div class="container">
    <h1>Latest videos</h1>
    <div id="player-wrapper"></div>
    <% @videos.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.each do |video| %>
          <% if video %>
            <div class="col-md-4">
              <div class="yt_video thumbnail">
                <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                                      class: 'img-rounded'),
                            "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
                <div class="caption">
                  <h5><%= video.title %></h5>
                  <p>Published at <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                  <p>
                    <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %>
                    <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>
 
  <%= form_for @video do |f| %>
    <%= render 'shared/error_messages', object: @video %>
 
    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>
 
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>