config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :entries,       only: [:index]
  resources :videos,        only: [:index, :new, :create]
  resources :video_uploads, only: [:new, :create]
  resources :comments,      only: [:new, :create]
  resources :messages,      only: [:new, :create, :index]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy', as: :logout
  get    'about'    => 'static_pages#about'
  get    'social'   => 'static_pages#social'
  get    'search'   => 'search#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  match '*path' => 'application#routing_error', via: :all
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

	<div class="alert alert-danger">
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
			<% end %>
		</ul>
	</div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="tweets">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<div class="paginate">
	<%= will_paginate @feed_items, renderer: BootstrapPagination::Rails %>
</div><% end %>

app/views/shared/_feed_item.html.erb
<li class="tweet clearfix" id="<%= feed_item.id %>">
	<div class="gravatar">
	<%= image_tag feed_item.user.avatar.url(:thumb) %>
	</div>
	<div class="content">
		<div class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</div>
		<div class="tweet-content">
			<%= wrap(feed_item.content) %>
		</div>
		<div class="tweet-footer">
		<Posted>
			<%= time_ago_in_words(feed_item.created_at) %> ago.
		</Posted>
		<% if current_user?(feed_item.user) %>
			<div class="tweet-actions">
				<%= link_to "delete", feed_item, method: :delete, data: { confirm: "You sure?" }, 
				title: feed_item.content %>
			</div>
		<% end %>
		</div>
	</div>
</li>

app/views/shared/_follow.html.slim
= form_for(current_user.relationships.build(followed_id: @user.id)) do |f|
  div = f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-large btn-primary"

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'shared/unfollow' %>
		<% else %>
			<%= render 'shared/follow' %>
		<% end %>
	</div>
<% end %>

app/views/shared/_profile.html.erb
<div class="profile clearfix">
	<%= image_tag @user.avatar.url(:medium) %>
		<div>
			<%= link_to "@", @user %><%= link_to @user.slug, @user %>
		<div>
			<%= @user.name %>
		</div>
		<div>
			Join Date: <%= @user.created_at.strftime("%B %d, %Y") %>
		</div>

	<%= render 'shared/follow_form' if signed_in? %>

</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<table>
		<tr>
			<th>Posts</th>
			<th>Following</th>
			<th>Followers</th>
		</tr>
		<tr>
			<td>
				<%= link_to @user.tweets.count, user_path(@user) %>
			</td>
			<td>
				<%= link_to @user.followed_users.count, following_user_path(@user) %>
			</td>
			<td>
				<%= link_to @user.followers.count, followers_user_path(@user) %>
			</td>
		</tr>
	</table>
</div>

app/views/shared/_tweet_form.html.erb
<div class="tweet-box">
<%= form_for(@tweet) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-default" %>
<% end %>

app/views/shared/_user_info.html.erb
<% @user ||= current_user%>
<%= render 'shared/profile' %>
<%= render 'shared/stats' %>
<%= render 'shared/tweet_form' %>

app/views/shared/_users.html.erb
<% @user ||= current_user %>
<%= render 'shared/profile' %>
<%= render 'shared/stats' %>
<%= render 'shared/tweet_form' %>