config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :entries,       only: [:index]
  resources :videos,        only: [:index, :new, :create]
  resources :video_uploads, only: [:new, :create]
  resources :comments,      only: [:new, :create]
  resources :messages,      only: [:new, :create, :index]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy', as: :logout
  get    'about'    => 'static_pages#about'
  get    'social'   => 'static_pages#social'
  get    'search'   => 'search#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  match '*path' => 'application#routing_error', via: :all
  
end

app/views/layouts/_footer.html.erb
<hr />

<footer class="footer">
 <div class="col-md-12 text-center"><p>OverTime<br>Social Media For Sports</p></div>
<!--login modal-->
<div id="loginModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h2 class="text-center"><%= image_tag 'login.png' %><br>Login</h2>
    </div>
    <div class="modal-body">
      <%= form_tag sessions_path, method: "POST", class: "form col-md-12 center-block" do |f| %>
        <div class="form-group">
          <%= text_field_tag :email, params[:email], class: "form-control", placeholder: "Email" %>
        </div>
        <div class="form-group">
          <%= password_field_tag :password, "", class: "form-control", placeholder: "Password" %>
        </div>

          <%= submit_tag "Log in", class: "btn btn-default" %> 
        <% end %>
        <span class="pull-right"><a href="/users/new">Register</a></span><span><a href="#">Need help?</a></span>
    </div>
    <div class="modal-footer">
      <div class="col-md-12">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
	  </div>	
    </div>
  </div>
  </div>
</div>


<!--about modal-->
<div id="aboutModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h2 class="text-center">About</h2>
      </div>
      <div class="modal-body">
          <div class="col-md-12 text-center">
            OverTime<br>
            Brought to you by Imran<br>
            Follow me on Twitter! @TheREALSuMP
          </div>
      </div>
      <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
      </div>
  </div>
  </div>
</div>
	<!-- script references -->
		
	</body>
</html>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top header">
  <div class="col-md-12">
    <div class="navbar-header">
      
      <a href="#" class="navbar-brand">OverTime</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
      <i class="glyphicon glyphicon-search"></i>
      </button>
    </div>
    <% if signed_in? %>
    <div class="collapse navbar-collapse" id="navbar-collapse1">
      <%= form_tag search_path, {method: :get, authentication: false, id: 'search-form', class: 'navbar-form pull-left'} do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
      
    <% end %>
 </div> 
</nav>
<% if signed_in? %>
<div class="navbar navbar-default" id="subnav">
<div class="col-md-12">
    <div class="navbar-header">
      
      
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse2">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
  
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse2">
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to 'Home', user_path(current_user) %></li>
         <li><%= link_to 'News', entries_path %></li>
         <li><%= link_to 'Videos', videos_path %></li>
         <li><%= link_to 'Social', tweets_path %></li>
         <li><a href="/social">Profile</a></li>
         <li><%= link_to 'Users', users_path %></li>
         <% if signed_in? %>
         <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
         <% end %>
         <li><a href="#aboutModal" role="button" data-toggle="modal">About</a></li>
       </ul>
    </div>  
 </div> 
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fanzone</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<link href="stylesheets/styles.css" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value|%>
			<div class="alert alert-<%= key %>">
		<%= value %>
	</div>
		<% end %>
		
		<%= yield %>

		<%= render 'layouts/footer' %>
</div>
</body>
</html>